dist: trusty
language: cpp
before_script:
 - git clone https://bitbucket.org/chromiumembedded/java-cef.git src
 - cd src && mkdir jcef_build && cd jcef_build
script:
 - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
 - make -j4
