# Operating system (build VM template)
os: Visual Studio 2015

# clone directory
clone_folder: c:\projects\java-cef

platform:
  - win32
  - x64

configuration:
  - Release

environment:
  matrix:
  - buildType: win32
    generatorName: Visual Studio 14
    JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
  - buildType: win64
    generatorName: Visual Studio 14 Win64
    JAVA_HOME: C:\Program Files\Java\jdk1.8.0

matrix:
  exclude:
    - platform: x64
      buildType: win32
    - platform: win32
      buildType: win64

before_build:
  - SET PATH=%JAVA_HOME%;%PATH%
  #- git clone --depth=1 https://bitbucket.org/chromiumembedded/java-cef.git c:\projects\java-cef\src
  - git clone --depth=1 https://bitbucket.org/guusdk/java-cef.git c:\projects\java-cef\src
  - echo "Running cmake..."
  - cd c:\projects\java-cef\src
  - mkdir jcef_build
  - cd jcef_build
  - cmake -G "%generatorName%" ..
  - echo "Building the JCEF Java classes..."
  - cd c:\projects\java-cef\src\tools
  - compile.bat "%buildType%"

after_build:
  - echo "Making distribution..."
  - cd c:\projects\java-cef\src\tools\
  - make_distrib.bat %buildType%
  - cd c:\projects\java-cef\src\binary_distrib
  - 7z a jcef-%buildType%-distribution.zip %buildType%

artifacts:
  - path: src\binary_distrib\jcef-%buildType%-distribution.zip
    name: jcef-%buildType%-distribution

deploy:
- provider: GitHub
  auth_token:
    secure: A3RVE8hwnjT87sIRTprQ0FwoAYGd8bvXwYBUki9OmX4A37XOo7wiP2dzYZxI/LCqq1DMCKnJdNpCSaf2PnBE29HSdNC1hbS4/8u077gb2uI=
  artifact: jcef-win32-distribution,jcef-win64-distribution
  draft: true
