# Operating system (build VM template)
os: Visual Studio 2015

# clone directory
clone_folder: c:\projects\java-cef

platform:
  - windows32

configuration:
  - Release

# scripts to run before build
before_build:
  - git clone --depth=1 https://bitbucket.org/chromiumembedded/java-cef.git c:\projects\java-cef\src
  - echo Running cmake...
  - cd c:\projects\java-cef\src
  - mkdir jcef_build
  - cd jcef_build
  - cmake -G "Visual Studio 14" ..
