# Operating system (build VM template)
os: Visual Studio 2015

# clone directory
clone_folder: c:\projects\java-cef

platform:
  - win32
  - x64

configuration:
  - Release

environment:
  matrix:
  - generatorName: Visual Studio 14
    JAVAHOME: C:\Program Files (x86)\Java\jdk1.8.0
  - generatorName: Visual Studio 14 Win64
    JAVAHOME: C:\Program Files\Java\jdk1.8.0

matrix:
  exclude:
    - platform: x64
      generatorName: Visual Studio 14
    - platform: win32
      generatorName: Visual Studio 14 Win64

# scripts to run before build
before_build:
  - setx -m JAVA_HOME "%JAVAHOME%"
  - echo %JAVA_HOME%
  - echo %JAVAHOME%
  - git clone --depth=1 https://bitbucket.org/chromiumembedded/java-cef.git c:\projects\java-cef\src
  - echo Running cmake...
  - cd c:\projects\java-cef\src
  - mkdir jcef_build
  - cd jcef_build
  - cmake -G "%generatorName%" ..
  - echo %JAVA_HOME%
  - echo %JAVAHOME%
